### ISSUE TITLE
record language when not the default

### ISSUE THREAD

**Issue by eroux** [OpenPecha/Toolkit#164]
Google OCR returns the language it detected for each page. This should be preserved in the opf, possibly in a language layer. The layer would not have to have a character range for each page, but instead one character range per area of the same language, so it would usually be very small and have just a few entries, for when there is a page in Chinese or English

**Comment by eroux** [comment]
Just to record what I said on Slack:

The main yml file would contain:

```yml
    default_language: bo
```

(`bo` or anything else), and it could be overwritten at the volume / base level in the main yml file. In addition to that, when necessary (which might not always be the case), there should be a new layer, `language`, that would indicate the character ranges where the language is different. The layer would just merge everything that's consecutive, it wouldn't have one annotation per word or page. For instance in a scenario where page 1 to 10 are in English, and then page 13, and the rest is in Tibetan, we would have: `default_language: bo` in the main yml and the following layer:

```yml
annotation_id_1:
     language: en
     start: 0
     end: 123456 (the final character of page 10)
annotation_id_2:
    language: en
    start: 4567989 (the first character of page 13)
    end: 789123 (the last character of page 13)
```
