### ISSUE TITLE
importing Norbu Ketaka etexts

### ISSUE THREAD

**Issue by eroux** [OpenPecha/Toolkit#208]
We received a big contribution (~380,000 pages) from a project named Norbu Ketaka. The import is composed of csv files, one per volume. Here's an excerpt from `W4PD759-I4PD902.csv`:

```csv
W4PD759,I4PD902,I4PD9020005,1,༄༅། །ཟངས་མདོག་དཔལ་རིའི་སྨོན་ལམ་གྱི་བསྡུས་འགྲེལ་རྣམ་གྲོལ་ནོར་བུའི་ཐེམ་སྐས་ཞེས་བྱ་བ་བཞུགས་སོ། །
W4PD759,I4PD902,I4PD9020006,1,༄༅། །རྒྱལ་ཀུན་གསང་གསུམ་ཡེ་ཤེས་སྒྱུ་མའི་འཕྲུལ། །ངོ་མཚར་རྨད་བྱུང་འཇིགས་བྲལ་རྡོ་རྗེའི་
W4PD759,I4PD902,I4PD9020006,2,སྐུར། །རྩོད་ལྡན་སྙིགས་མའི་མགོན་དུ་ཡོངས་བཞེངས་པ། །གྲུབ་བརྒྱའི་གཙུག་རྒྱན་པདྨ་ཀཱ་རར་
W4PD759,I4PD902,I4PD9020006,3,འདུད། །དེ་ལ་འདིར་ཨོ་རྒྱན་པདྨའི་རྒྱལ་ཚབ་ཏུ་མངའ་གསོལ་བའི་རང་རེ་དམུ་རྒོད་སྙིགས་མའི་སྐྱེ་འགྲོ་རྣམས་
W4PD759,I4PD902,I4PD9020006,4,འདུལ་ཕྱིར་བསམ་བཞིན་དུ་སྤྲུལ་བའི་ཟློས་གར་མངོན་མཁན་སློབ་ཆོས་གསུམ་སྙིགས་མའི་མགོན།    
W4PD759,I4PD902,I4PD9020003,1,༄༅། །ཁང་སར་བསྟན་པའི་དབང་ཕྱུག་གི་གསུང་འབུམ་བཞུགས་སོ། །
W4PD759,I4PD902,I4PD9020004,1,༄༅།།བཀྲ་ཤིས་པད་མའི་གླེགས་བམ་བཞུགས་སོ།།
```

- column 1 is scan id
- column 2 is image group id
- column 3 is the image name (without the extension)
- column 4 is the line number

note that the lines are not necessarily in order. All the files are in the same folder

They're made based on the BDRC OCR but cleaned up.

The project requested this description to be added, it should be in all the meta.yml:

```
The proofread texts are donated by the Norbu Ketaka project led by Queenie Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu .
```

**Comment by jungtop** [comment]
@eroux Can you share me the files. Also, is there any information for each volume file? for instance title,etc.

**Comment by eroux** [comment]
Hi @jungtop , thanks for taking care of this! The file is on http://eroux.fr/08152022_queenieluo.zip , there are two steps for the import:

### import to s3

The first step is to move these files in their relevant s3 folder. For instance `W1K2118-I1K2126.csv` should be copied to

```
s3://ocr.bdrc.io/Works/c7/W1K2118/norbuketaka/batch-0001/W1K2118-I1K2126.csv
```

and then for each folder, an `info.json` file must be created, containing 

```
{
   "timestamp": "2022-08-25T00:00:00Z"
}
```

(it can be hardcoded, this is the date when we received the files)

### import to openpecha

Once the files are well organized on s3, a new formatter must be created in the toolkit. It will be quite similar to the ocr formatters and will need to call the BUDA api functions from the toolkit to get the title, author, etc.

**Comment by eroux** [comment]
note that in the final opf, the pagination layer should have the image file name extension added. This requires looking at the image list from the BUDA api

**Comment by eroux** [comment]
@jungtop any update on that?

**Comment by jungtop** [comment]
@eroux i have uploaded the files to s3 and the formatter is in progress.

**Comment by eroux** [comment]
@jungtop you uploaded the files in the wrong place, you added `s3://ocr.bdrc.io/` in the prefix of the files on s3, for instance

`s3://ocr.bdrc.io/s3://ocr.bdrc.io/Works/0e/W1KG17199/`

should be in

`s3://ocr.bdrc.io/Works/0e/W1KG17199/` 

instead. An s3 url is:

`s3://{bucket_name}/{key_name}`

so when I say

`s3://ocr.bdrc.io/Works/0e/W1KG17199/` it means:

- `bucket_name` = `ocr.bdrc.io`
- `key` = `Works/0e/W1KG17199/`

I've moved the files to the right place but please keep it in mind for the future.

We need to have the opfs done by January 15th, do you think that could work?

**Comment by eroux** [comment]
@jungtop any update on the opfs?

**Comment by jungtop** [comment]
Hey Sorry for the late reply,the opfs have been already created but yet to be published in OpenPecha-Data.I will upload the opfs soon as i have reached the limit to upload content in github.The opfs can be done before Jan 15.

**Comment by eroux** [comment]
Ok thanks! Can you send an example opf in a zip file in this issue or by email so that I can double check? Also what Github content upload limit are you talking about?

**Comment by jungtop** [comment]
Here is a sample opf https://github.com/jungtop/I1A40C184.git . Since i have to upload more than 5k opf and opa ,the issue below arises


{"message": "You have exceeded a secondary rate limit and have been temporarily blocked from content creation. 
Please  retry your request again later.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits%22%7D}

**Comment by eroux** [comment]
thanks! a few changes needed though:

- most importantly, there should be one opf per scan id (ex: W3PD1002), in your example it looks like you created one opf per volume (I1KG81129)
- in the [pagination layer](https://github.com/jungtop/I1A40C184/blob/main/I1A40C184.opf/layers/0B42/Pagination.yml) you should remove the `metadata` key
- the base id should be the image group name, in this case `I1KG81129`

In [meta.yml](https://github.com/jungtop/I1A40C184/blob/main/I1A40C184.opf/meta.yml), a lot should be changed, here's a new version:

```yml
id: I1A40C184
ocr_import_info:
  bdrc_scan_id: W3PD1002
  source: bdrc
  ocr_info:
    timestamp: '2022-08-25T00:00:00Z'
  batch_id: batch001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:26:20.614553+00:00'
last_modified: 2022-08-25T00:00:00Z
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3PD1002
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3PD1002
  copyright_status: http://purl.bdrc.io/resource/CopyrightClaimed
  title: གསུང་འབུམ། མཁྱེན་བརྩེའི་དབང་པོ།
  author: མཁྱེན་བརྩེའི་དབང་པོ།
quality: null
bases:
  I1KG81129:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81129
      total_pages: 590
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG81129.txt
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by
    Queenie Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard
    van der Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
```

`ocr_info` should be exactly the content of `s3://ocr.bdrc.io/Works/08/W3PD1002/norbuketaka/batch-0001/info.json`, it shouldn't be hardcoded. `parser` should be changed to a link to the Python file that you use for the import

Please communicate once you've finished something so that we can check and finish the task
